services:
  # Backend API service
  - type: web
    name: ai-image-generator-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  # Frontend static site
  - type: web
    name: ai-image-generator-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 16.0.0 